version: '3'

services:
  drupal:
    image: drupal:9.3.13
    ports:
      - 8070:80
    volumes:
      - drupal_modules:/var/www/html/modules
      - drupal_profiles:/var/www/html/profiles
      - drupal_sites:/var/www/html/sites
      - drupal_themes:/var/www/html/themes
  postgres:
    image: postgres:14.3
    environment:
      POSTGRES_PASSWORD: blah
      POSTGRES_USER: Sean
      POSTGRES_DB: mypostgres

volumes:
  drupal_modules: 
  drupal_profiles:
  drupal_sites:
  drupal_themes:   
