apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: myapp-nginx
    type: frontend
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
    - name: log-agent
      image: log-agent
