# version isn't needed as of 2020 for docker compose CLI. 
# All 2.x and 3.x features supported
# version: '2'

# based off compose-sample-2, only we build nginx.conf into image
# uses sample HTML static site from https://startbootstrap.com/themes/agency/

services:
  proxy:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    image: nginx-custom
    ports:
      - '8090:80'
  web:
    image: httpd
    volumes:
      # This is a bind mounting as it starts with a '/'. So any change to the files in there will be reflected inside the running container on localhost
      - ./html:/usr/local/apache2/htdocs/
