apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
spec:
  containers:
  - name: ubuntu
    image: ubuntu
    envFrom:
      - secretRef:
	  name: app-secret

# Or to inject a single secret
apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
spec:
  containers:
  - name: ubuntu
    image: ubuntu
    env:
      - name: DB_PASSWORD
        valueFrom:
          secretKeyRef:
	    name: app-secret
	    key: DB_PASSWORD
