apiVersion: apps/v1
kind: Deployment
metadata:
        name: red
spec:
        template:
                metadata:
                        name: nginx-red-pod
                        labels:
                                color: red
                spec:
                        containers:
                          - image: nginx
                            name: nginx-container
                        affinity:
                                nodeAffinity:
                                        requiredDuringSchedulingIgnoredDuringExecution:
                                                nodeSelectorTerms:
                                                  - matchExpressions:
                                                          - key: node-role.kubernetes.io/master
                                                            operator: Exists
        replicas: 2
        selector:
                matchLabels:
                        color: red
