apiVersion: apps/v1
kind: Deployment
metadata:
        name: blue
spec:
        template:
                metadata:
                        name: nginx-blue-pod
                        labels:
                                app: nginx
                                color: blue
                spec:
                        containers:
                          - image: nginx
                            name: nginx-container
                        affinity:
                                nodeAffinity:
                                        requiredDuringSchedulingIgnoredDuringExecution:
                                                nodeSelectorTerms:
                                                  - matchExpressions:
                                                          - key: kubernetes.io/hostname
                                                            operator: In
                                                            values:
                                                                    -  minikube
        replicas: 3
        selector:
                matchLabels:
                        app: nginx
                        color: blue
