apiVersion: apps/v1
kind: DaemonSet
metadata:
        name: elasticsearch
        namespace: kube-system
spec:
        template:
                metadata:
                        name: FluentD-elasticsearch
                        labels:
                                app: elasticsearch
                spec:
                        containers:
                                - image: k8s.gcr.io/fluentd-elasticsearch:1.20
                                  name: fluentd-elasticsearch
        selector:
                matchLabels:
                        app: elasticsearch
