apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    type: nginx-deployment
spec:
  template:
    metadata:
      name: nginx-pod
      labels:
        type: nginx-proxy
    spec:
      containers:
        - name: nginx-container
          image: nginx
          ports:
            - containerPort: 80
    
  replicas: 2
  selector:
    matchLabels:
      type: nginx-proxy
