apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    kubernetes_type: nginx-service
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      protocol: TCP
  selector:
    app: myapp-nginx
    type: frontend
