apiVersion: v1
kind: Service
metadata:
  name: mynginx-service
  labels:
    type: nginx-service
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      protocol: TCP
  selector:
    type: nginx-proxy
