apiVersion: v1
kind: Service
metadata:
  name: nginx-app-service
  labels:
    type: nginx-deployment
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      protocol: TCP
  selector:
    type: nginx-proxy
